env:
  global:
  - REPO_NAME=aliyun-odps-python-sdk
  - secure: Ugp4WH99iOMKE7n79frD33jZzlr+C0djnSNl2igiqPVlEdJxoSHtLV3n8wjp60xAPrdt64av0k0KuINOwN8lShdpDSamsxh890sMW6bfrY2u8+wCxG0cz6jIB3svrw/vZzZRChPaY9TE8E8kNHpRL8Wh3Ro3BY71Y9gfVOyx+x8Olxz7LV64tplxVTK72kjMZNNLQl6rYXRLlFZlKOP7iSG8EKcv2jreVv7voQ1D9AYGz+539MzcPIw+Qbp9jD6+pekUjSHknJrMX12163VJnKXD4AskZNIsH0W6EkTGBXM9d8hg2N8V2QhEeK4pQjG2st6NDX6zKW/0zz/q2S51g3XWDrflyS/aBUCZb0zfuy5xuqZSccXFmBr7VmEtN7GP1zRU0NC0N6Th5cWt+VzvZ3ssvK5hmwV6B9m+eByrLFuBvgAN6eLXybe6b3xMVz8FgC5Sar9hfFgUrhLG7Z/rUXmd2dYAQcTj4yFbw9+/KHMfTcnrQNcoOtlyrR7S06NIR5+pPUenpXD9eIL8eltMGDDElBrjVLC48H4EjHlXwonAzwpNOTy3Rb9cnV6Zo7mTsQUqLqEKGaUDAXUGZ2ZSI2MQ+slPTAP7Z4ejgJPaa4CHdhUXbBy+LwT0bcTWhRtNUs7QTGPDsZYWtpTDYdnLV5xdbNk+LwRIZyWX8eCAAQA=

notifications:
  email: false

  
language: python
python: 3.5

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp27-cp27m
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp35-cp35m
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp36-cp36m
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PYVER=cp27-cp27m
           PRE_CMD=linux32
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PYVER=cp35-cp35m
           PRE_CMD=linux32
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PYVER=cp36-cp36m
           PRE_CMD=linux32

install:
  - ls

script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]
  - then
  - travis/osx-wheel.sh
  - else 
  - docker pull $DOCKER_IMAGE
  - export PYVER=$PYVER
  - sudo chmod 777 travis/linux-wheel.sh
  - sudo chmod 777 travis/osx-wheel.sh
  - docker run --rm -e "PYVER=$PYVER" -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/linux-wheel.sh
  - fi
  - ls dist
  
after_success:
  - echo "[distutils]"                                  > ~/.pypirc
  - echo "index-servers ="                             >> ~/.pypirc
  - echo "    testpypi"                                >> ~/.pypirc
  - echo "[testpypi]"                                  >> ~/.pypirc
  - echo "repository=https://testpypi.python.org/pypi" >> ~/.pypirc
  - echo "username=pyodps"                             >> ~/.pypirc
  - echo "password=$PSD"                               >> ~/.pypirc
  - pip install twine
  - twine upload -r testpypi --skip-existing dist/*.whl
