env:
  global:
  - REPO_NAME=aliyun-odps-python-sdk
  - secure:weOO6qPWoYWlBd5Ofphtocys5quHi/Jet6lTM4WdTsTAa+M9JGYMd95YplEX/y7tHPXvCkF83XJlWRQvfa3lY1HV/22+w83WT625qGaprDYMx6lssAD8ikmZ6jj2djOaTwP3qNbR9CgwRO+poA5s87DfWCdX6wNcO37je/MJr3jsiYhQwqzUxsrPpq/wFBB17lW+rpDUx8q1yPJ6tHBEKzjR9L7k/TB2GcCtwXmLcaJrOb4BMQYhv+XJwRs5zhmko3QsqGoWF7tlpUsUJWT0Fgh67NDM+T8X01fJbUx6/k/TsKKgBWq446eKNBlOxy67yCwFSo33ki/imcoHaePTAkFjqsipNpOyh3FfCZWKxz3pK0sIe2smB98eBDSDg6zjkfq4WKEX2vUNzfRoQMjiBWUtZFhSuWLQBfKz6bnWVERSKjABtTrOUBfHCvrrWw98Ji0wcdvogGLhT0XgTvuJnmNaZRPQmDgfdSquLF6nXlOhO7ysMzUw9pF+V7PmhABF8tokHpx7Py/1Uu1j/LGoYSRJv+al2I/usk9BLw/S1UALw/7usXAw0xS8p/wPqsMea7qs5U5qlyIYKr3YSqiEsL09e4/KksGzFYVN5/jMOShI+mPepFfb2yEdlDe/nNwmLKN0cDkSthTyB4l+hvbuVI0RgWv/vmZjkz7O68sf9VA=
notifications:
  email: false


  
language: python
python: 3.5

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp27-cp27m
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp35-cp35m
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp36-cp36m
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PYVER=cp27-cp27m
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PYVER=cp35-cp35m
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PYVER=cp36-cp36m
    - os: osx
      language: generic
      env: PYTHON=2.7.12
    - os: osx
      language: generic
      env: PYTHON=3.5.3
    - os: osx
      language: generic
      env: PYTHON=3.6.1

install:
  - sudo chmod 777 bin/travis/*
  - bin/travis/${TRAVIS_OS_NAME}"-install.sh"
  #- bin/travis/${TRAVIS_OS_NAME}"-test.sh"

script:
  - ls dist
  
after_success:
  - echo "[distutils]"                                  > ~/.pypirc
  - echo "index-servers ="                             >> ~/.pypirc
  - echo "    pypi"                                    >> ~/.pypirc
  - echo "[pypi]"                                      >> ~/.pypirc
  - echo "repository=https://upload.pypi.org/legacy/"  >> ~/.pypirc
  - echo "username=pyodps"                             >> ~/.pypirc
  - echo "password=$PSD"                               >> ~/.pypirc
  - pip install twine
  # upload only commit with tag
  - if [ "$TRAVIS_TAG" ]; then
    twine upload -r pypi --skip-existing dist/*.whl
    fi


