language: python

env:
  global:
    - secure: "Yg8LeAzdFMtQH5fh/2xDx72nsIn7RzKZb3udcHaY5O6qge8Dys+D+G907xTbO1J+z1H1ydNbF0Ogw12F9zov9iYuTrpZGgtK7TveJHfO5tm3Pp80WAYZkz+5Zv+egkRtiNf9aNwYUBxmvRSKqyjL1BXv4XElQ/8crgiX/NHqMITuMbrPys81AtkVg58RG9Lddbu3oePmPpUeJSluMwy3OtG/CCQPEGo/NReU8pFmn20apIZPu290AC4FrkakKhA99cHdEbefoBQgpPbnAh9obqI6hZquUwmr4Z+2QIkKZVKDxoouG0Zt/2m1/T9/8nL21zg9gmXgt78dGTsIYGnGhLbBYnW2t/sqz87RAQhTsSfB9nmKbeu9sZB8TQV2+BtwTpv2iaRa8zX7B2BtcbKpUuqtXY9HvgbOJI1IsWoq1g52ee6SulT3Jgq91sqepIcq6KxTbcTIZglVllR3SC6mqZlbhLzNN5DqjW/6JCdOPbGv43VAHslnYZwd1qsGaVRBAddJb2Awo5oJRFocq7HFdO+py111gW7s8PwRYzQsLaX8yJSYTWHwT+1v1bNluCZOJqrCneP/Er1aIUEOxQgKmg4J9WnkWoc17JBebk9kfgnMlS3qQiIrHwO6jtnQ+XMozIPXeaV11tHngXDDHU9wtbBV9hoCvWjagiLErhFAGSQ="

matrix:
    include:
        - os: linux
          sudo: required
          python: 3.5
        - os: linux
          sudo: required
          python: 2.7
        - os: osx
          language: generic
          python: 2.7
        - os: osx
          language: generic
          python: 3.5
install:
  - pip install --upgrade pip
  - pip install wheel
  - pip install -r requirements-full.txt
  - pip install cython
  
script:
  - python setup.py install
  - python setup.py bdist_wheel

deploy:
  skip_cleanup: true
  provider: pypi
  distributions: bdist_wheel
  server: https://testpypi.python.org/pypi
  user: pyodps
  password:
    secure: Yg8LeAzdFMtQH5fh/2xDx72nsIn7RzKZb3udcHaY5O6qge8Dys+D+G907xTbO1J+z1H1ydNbF0Ogw12F9zov9iYuTrpZGgtK7TveJHfO5tm3Pp80WAYZkz+5Zv+egkRtiNf9aNwYUBxmvRSKqyjL1BXv4XElQ/8crgiX/NHqMITuMbrPys81AtkVg58RG9Lddbu3oePmPpUeJSluMwy3OtG/CCQPEGo/NReU8pFmn20apIZPu290AC4FrkakKhA99cHdEbefoBQgpPbnAh9obqI6hZquUwmr4Z+2QIkKZVKDxoouG0Zt/2m1/T9/8nL21zg9gmXgt78dGTsIYGnGhLbBYnW2t/sqz87RAQhTsSfB9nmKbeu9sZB8TQV2+BtwTpv2iaRa8zX7B2BtcbKpUuqtXY9HvgbOJI1IsWoq1g52ee6SulT3Jgq91sqepIcq6KxTbcTIZglVllR3SC6mqZlbhLzNN5DqjW/6JCdOPbGv43VAHslnYZwd1qsGaVRBAddJb2Awo5oJRFocq7HFdO+py111gW7s8PwRYzQsLaX8yJSYTWHwT+1v1bNluCZOJqrCneP/Er1aIUEOxQgKmg4J9WnkWoc17JBebk9kfgnMlS3qQiIrHwO6jtnQ+XMozIPXeaV11tHngXDDHU9wtbBV9hoCvWjagiLErhFAGSQ=

  on:
    branch: testPyPI
